<a href="https://colab.research.google.com/github/HjayejMohamed/NLP/blob/main/nlp_with_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Dense,Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[14, 19]

In [4]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]

In [5]:
print(encoded_reviews)

[[4, 1], [14, 19], [21, 3], [17, 15, 23], [5, 7, 4], [25, 1], [9, 7, 9], [8, 8], [8, 27], [5, 23]]


In [6]:
padding_reviews=pad_sequences(encoded_reviews,maxlen=4,padding='post')
padding_reviews

array([[ 4,  1,  0,  0],
       [14, 19,  0,  0],
       [21,  3,  0,  0],
       [17, 15, 23,  0],
       [ 5,  7,  4,  0],
       [25,  1,  0,  0],
       [ 9,  7,  9,  0],
       [ 8,  8,  0,  0],
       [ 8, 27,  0,  0],
       [ 5, 23,  0,  0]], dtype=int32)

In [10]:
vocab_size=30
embeded_vector_size = 5
max_length=4
model=Sequential([
  Embedding(vocab_size,embeded_vector_size,input_length=max_length),
  Flatten(),
  Dense(1,activation='sigmoid')
])

In [11]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(padding_reviews,sentiment,epochs=60,verbose=0)

In [19]:
loss, accuracy = model.evaluate(padding_reviews, sentiment)
accuracy

1/1 [==============================] - 0s 150ms/step - loss: 0.6079 - accuracy: 1.0000


1.0

In [16]:
padding_reviews[0]

array([4, 1, 0, 0], dtype=int32)

In [31]:
model.predict(padding_reviews[7].reshape(-1,1))

array([[0.45160213]], dtype=float32)

In [27]:
padding_reviews[0].reshape(-1,1)

array([[4],
       [1],
       [0],
       [0]], dtype=int32)